### ISSUE TITLE
Local Save does not work

### ISSUE THREAD

**Issue by JasonCostanza** [JasonCostanza/Dice-Vault#5]
Currently, attempting to save the saved rolls locally does not work.

Error in console pointed to an undefined JSON element

```
Uncaught SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at vault.js:55:26
    at Array.map (<anonymous>)
    at saveCurrentRolls (vault.js:51:55)
    at save (vault.js:126:5)
    at HTMLButtonElement.onclick (vault.html:95:48)

**Comment by JasonCostanza** [comment]
This is fixed in next update.
